import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import Header from "@/components/ui/header";
import Sidebar from "@/components/ui/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Routes = [
  { label: "대시보드", route: "/" },
  { label: "상세비용탐색기", route: "/cost" },
  { label: "예산 관리 & 알림 설정", route: "/budgets" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Provider>
          <Header Routes={Routes} />
          <div className="flex flex-1 flex-col md:flex-row">
            <Sidebar labels={Routes} />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
