import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import Header from "@/components/ui/header";
import Sidebar from "@/components/ui/Sidebar";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Routes = [
  { label: "대시보드", route: "/" },
  { label: "상세비용탐색기", route: "/cost" },
  { label: "예산 관리 & 알림 설정", route: "/budgets" },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const isLoggedIn = !!user;

  return (
    <html lang="ko" className={`h-full antialiased`}>
      <body className="flex h-full flex-col overflow-hidden">
        <Provider>
          <Header Routes={Routes} isLoggedIn={isLoggedIn} />
          <div className="flex min-h-0 flex-1 flex-col md:flex-row">
            {isLoggedIn && <Sidebar labels={Routes} />}
            <div className="min-h-0 flex-1 overflow-y-auto">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
